package com.oceanview.resort.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Bill entity representing a financial bill for a reservation at Ocean View Resort.
 *
 * <p>Contains itemized charges, tax calculations, optional discounts, and tracks
 * payment status. Uses {@link BigDecimal} for all monetary fields to ensure
 * precision.</p>
 *
 * <h3>Calculation formula</h3>
 * <pre>
 *   subtotal    = numNights × roomRate
 *   taxAmount   = subtotal  × (taxRate / 100)
 *   totalAmount = subtotal  + taxAmount − discountAmount
 * </pre>
 *
 * <h3>Relationships</h3>
 * <ul>
 *   <li>{@code reservation} – one-to-one with {@link Reservation} (owning side, lazy).</li>
 *   <li>{@code payments}     – one-to-many with {@link Payment} (mapped by
 *       {@code Payment.bill}). Lazy-loaded and excluded from
 *       {@code toString()} / {@code equals()} / {@code hashCode()}.</li>
 * </ul>
 *
 * @see Reservation
 * @see Payment
 */
@Entity
@Table(name = "bills", indexes = {
        @Index(name = "idx_bills_payment_status", columnList = "payment_status")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"reservation", "payments"})
@ToString(exclude = {"reservation", "payments"})
public class Bill {

    /** UUID primary key, auto-generated by JPA. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** The reservation this bill belongs to. */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reservation_id", unique = true, nullable = false)
    private Reservation reservation;

    /** Number of nights the room was occupied. */
    @Column(name = "num_nights", nullable = false)
    @Min(value = 1, message = "Number of nights must be at least 1")
    private int numNights;

    /** Nightly room rate at the time of billing. */
    @Column(name = "room_rate", nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Room rate is required")
    @DecimalMin(value = "0.01", message = "Room rate must be positive")
    private BigDecimal roomRate;

    /** Subtotal before tax and discounts ({@code numNights × roomRate}). */
    @Column(nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Subtotal is required")
    private BigDecimal subtotal;

    /** Tax percentage applied to the subtotal; defaults to 10%. */
    @Column(name = "tax_rate", precision = 5, scale = 2)
    @Builder.Default
    private BigDecimal taxRate = new BigDecimal("10.00");

    /** Calculated tax amount ({@code subtotal × taxRate / 100}). */
    @Column(name = "tax_amount", nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Tax amount is required")
    private BigDecimal taxAmount;

    /** Discount amount deducted from the total; defaults to zero. */
    @Column(name = "discount_amount", precision = 10, scale = 2)
    @Builder.Default
    private BigDecimal discountAmount = BigDecimal.ZERO;

    /** Final amount due ({@code subtotal + taxAmount − discountAmount}). */
    @Column(name = "total_amount", nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Total amount is required")
    private BigDecimal totalAmount;

    /** Payment status string (e.g. UNPAID, PARTIALLY_PAID, PAID). */
    @Column(name = "payment_status", nullable = false, length = 20)
    @Builder.Default
    private String paymentStatus = "UNPAID";

    /** Timestamp of bill generation (set automatically, never updated). */
    @CreationTimestamp
    @Column(name = "generated_at", updatable = false)
    private LocalDateTime generatedAt;

    /**
     * Payments made against this bill.
     * Lazy-loaded; the owning side is {@link Payment#bill}.
     */
    @OneToMany(mappedBy = "bill", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    @Builder.Default
    private List<Payment> payments = new ArrayList<>();

    /**
     * Returns the outstanding balance (total amount minus sum of payments).
     *
     * @return the remaining amount due
     */
    @Transient
    public BigDecimal getOutstandingBalance() {
        BigDecimal paid = payments.stream()
                .map(Payment::getAmountPaid)
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        return totalAmount.subtract(paid);
    }

    /**
     * Checks whether the bill has been fully paid.
     *
     * @return {@code true} if payments cover the total amount
     */
    @Transient
    public boolean isFullyPaid() {
        return getOutstandingBalance().compareTo(BigDecimal.ZERO) <= 0;
    }
}
