package com.oceanview.resort.model;

import com.oceanview.resort.model.enums.PaymentMethod;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Payment entity representing a payment transaction against a {@link Bill}
 * at Ocean View Resort.
 *
 * <p>Supports multiple payment methods defined by {@link PaymentMethod}.
 * A single bill may have multiple partial payments until the outstanding
 * balance reaches zero.</p>
 *
 * <h3>Relationships</h3>
 * <ul>
 *   <li>{@code bill}        – many-to-one with {@link Bill} (lazy).</li>
 *   <li>{@code reservation} – many-to-one with {@link Reservation} (lazy, denormalised
 *       for convenience).</li>
 *   <li>{@code processedBy} – many-to-one with {@link User} – the staff member who
 *       processed this payment (optional, lazy).</li>
 * </ul>
 *
 * @see Bill
 * @see Reservation
 * @see PaymentMethod
 */
@Entity
@Table(name = "payments", indexes = {
        @Index(name = "idx_payments_bill", columnList = "bill_id"),
        @Index(name = "idx_payments_reservation", columnList = "reservation_id")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"bill", "reservation", "processedBy"})
@ToString(exclude = {"bill", "reservation", "processedBy"})
public class Payment {

    /** UUID primary key, auto-generated by JPA. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** The bill this payment is applied to. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "bill_id", nullable = false)
    private Bill bill;

    /** The reservation associated with this payment (denormalised reference). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "reservation_id", nullable = false)
    private Reservation reservation;

    /** Monetary amount paid in this transaction. */
    @Column(name = "amount_paid", nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Amount paid is required")
    @DecimalMin(value = "0.01", message = "Amount paid must be at least 0.01")
    private BigDecimal amountPaid;

    /** Method used for this payment. */
    @Enumerated(EnumType.STRING)
    @Column(name = "payment_method", nullable = false)
    @NotNull(message = "Payment method is required")
    private PaymentMethod paymentMethod;

    /** External transaction reference (card auth code, online txn ID, etc.). */
    @Column(name = "transaction_reference", length = 100)
    private String transactionReference;

    /** Timestamp of when the payment was recorded (set automatically). */
    @CreationTimestamp
    @Column(name = "payment_date", updatable = false)
    private LocalDateTime paymentDate;

    /** Staff member who processed this payment (optional). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "processed_by")
    private User processedBy;

    /** Optional notes or remarks about the payment. */
    @Column(columnDefinition = "TEXT")
    private String notes;
}
