package com.oceanview.resort.model;

import com.oceanview.resort.model.enums.ReservationStatus;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.temporal.ChronoUnit;

/**
 * Reservation entity representing a room booking at Ocean View Resort.
 *
 * <p>Links a {@link Customer} to a {@link Room} for a specific date range and
 * tracks the booking lifecycle through {@link ReservationStatus} transitions.</p>
 *
 * <h3>Relationships</h3>
 * <ul>
 *   <li>{@code customer} – many-to-one with {@link Customer} (lazy).</li>
 *   <li>{@code room}     – many-to-one with {@link Room} (lazy).</li>
 *   <li>{@code staff}    – many-to-one with {@link User} – the staff member who
 *       created/managed this reservation (optional, lazy).</li>
 *   <li>{@code bill}     – one-to-one with {@link Bill} (mapped by
 *       {@code Bill.reservation}, lazy). Set when the bill is generated.</li>
 * </ul>
 *
 * @see Customer
 * @see Room
 * @see Bill
 * @see ReservationStatus
 */
@Entity
@Table(name = "reservations", indexes = {
        @Index(name = "idx_reservations_customer", columnList = "customer_id"),
        @Index(name = "idx_reservations_room", columnList = "room_id"),
        @Index(name = "idx_reservations_dates", columnList = "check_in_date, check_out_date"),
        @Index(name = "idx_reservations_status", columnList = "status")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"customer", "room", "staff", "bill"})
@ToString(exclude = {"customer", "room", "staff", "bill"})
public class Reservation {

    /** UUID primary key, auto-generated by JPA. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /**
     * Unique reservation reference number.
     * Format: {@code OVR-YYYY-NNNNNN} (generated by {@code ReservationNumberGenerator}).
     */
    @Column(name = "reservation_number", unique = true, nullable = false, length = 20)
    private String reservationNumber;

    /** The customer who owns this reservation. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    /** The room reserved for this booking. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "room_id", nullable = false)
    private Room room;

    /** Staff member who created or last managed this reservation (optional). */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "staff_id")
    private User staff;

    /** Full name of the guest staying in the room. */
    @Column(name = "guest_name", nullable = false, length = 200)
    @NotBlank(message = "Guest name is required")
    @Size(max = 200, message = "Guest name must not exceed 200 characters")
    private String guestName;

    /** Postal / residential address of the guest. */
    @Column(name = "guest_address", columnDefinition = "TEXT")
    private String guestAddress;

    /** Contact phone number for the guest. */
    @Column(name = "guest_contact", nullable = false, length = 20)
    @NotBlank(message = "Guest contact is required")
    private String guestContact;

    /** Planned check-in date (must be today or in the future). */
    @Column(name = "check_in_date", nullable = false)
    @NotNull(message = "Check-in date is required")
    @FutureOrPresent(message = "Check-in date must be today or in the future")
    private LocalDate checkInDate;

    /** Planned check-out date (must be after check-in date). */
    @Column(name = "check_out_date", nullable = false)
    @NotNull(message = "Check-out date is required")
    @Future(message = "Check-out date must be in the future")
    private LocalDate checkOutDate;

    /** Number of guests for this reservation; defaults to 1. */
    @Column(name = "num_guests", nullable = false)
    @Min(value = 1, message = "At least one guest is required")
    @Builder.Default
    private int numGuests = 1;

    /** Any special requests from the guest (e.g. extra pillows, late check-out). */
    @Column(name = "special_requests", columnDefinition = "TEXT")
    private String specialRequests;

    /** Current lifecycle status of the reservation; defaults to {@link ReservationStatus#PENDING}. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @Builder.Default
    private ReservationStatus status = ReservationStatus.PENDING;

    /**
     * Bill generated for this reservation (inverse side).
     * {@code null} until a bill is explicitly generated.
     */
    @OneToOne(mappedBy = "reservation", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
    private Bill bill;

    /** Timestamp of record creation (set automatically, never updated). */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update (set automatically on every update). */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Calculates the number of nights between check-in and check-out.
     *
     * @return number of nights, or 0 if dates are not set
     */
    @Transient
    public long getNumberOfNights() {
        if (checkInDate == null || checkOutDate == null) {
            return 0;
        }
        return ChronoUnit.DAYS.between(checkInDate, checkOutDate);
    }
}
