package com.oceanview.resort.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.oceanview.resort.model.enums.RoomType;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * Room entity representing a hotel room at Ocean View Resort.
 *
 * <p>Contains room details including number, type, floor, capacity, nightly rate,
 * availability status, and amenities stored as a JSON string.</p>
 *
 * <h3>Relationships</h3>
 * <ul>
 *   <li>{@code reservations} – one-to-many relationship with {@link Reservation}
 *       (mapped by {@code Reservation.room}). Lazy-loaded and excluded from
 *       {@code toString()} / {@code equals()} / {@code hashCode()}.</li>
 * </ul>
 *
 * @see RoomType
 * @see Reservation
 */
@Entity
@Table(name = "rooms", indexes = {
        @Index(name = "idx_rooms_type", columnList = "room_type"),
        @Index(name = "idx_rooms_available", columnList = "is_available")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(exclude = {"reservations"})
@ToString(exclude = {"reservations"})
public class Room {

    /** UUID primary key, auto-generated by JPA. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Unique room number displayed to guests (e.g. "101", "P-01"). */
    @Column(name = "room_number", unique = true, nullable = false, length = 10)
    @NotBlank(message = "Room number is required")
    @Size(max = 10, message = "Room number must not exceed 10 characters")
    private String roomNumber;

    /** Category/tier of the room. */
    @Enumerated(EnumType.STRING)
    @Column(name = "room_type", nullable = false)
    @NotNull(message = "Room type is required")
    private RoomType roomType;

    /** Floor on which the room is located (1-based). */
    @Column(name = "floor_number", nullable = false)
    @NotNull(message = "Floor number is required")
    @Min(value = 1, message = "Floor number must be at least 1")
    private Integer floorNumber;

    /** Maximum guest capacity for this room. */
    @Column(nullable = false)
    @NotNull(message = "Capacity is required")
    @Min(value = 1, message = "Capacity must be at least 1")
    private Integer capacity;

    /** Nightly rate in the base currency. */
    @Column(name = "rate_per_night", nullable = false, precision = 10, scale = 2)
    @NotNull(message = "Rate per night is required")
    @DecimalMin(value = "0.01", message = "Rate per night must be positive")
    private BigDecimal ratePerNight;

    /** Optional textual description of the room. */
    @Column(columnDefinition = "TEXT")
    private String description;

    /** Whether the room is currently available for booking. */
    @Column(name = "is_available")
    @Builder.Default
    private boolean isAvailable = true;

    /**
     * Amenities associated with the room, stored as a JSON array string.
     * Example: {@code ["WiFi","TV","Mini Bar","Ocean View"]}
     */
    @Column(columnDefinition = "JSON")
    private String amenities;

    /** Timestamp of record creation (set automatically, never updated). */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /**
     * Reservations associated with this room.
     * Lazy-loaded; the owning side is {@link Reservation}.
     */
    @JsonIgnore
    @OneToMany(mappedBy = "room", fetch = FetchType.LAZY)
    @Builder.Default
    private List<Reservation> reservations = new ArrayList<>();
}
