package com.oceanview.resort.model;

import com.oceanview.resort.model.enums.UserRole;
import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.LocalDateTime;

/**
 * Base User entity representing all system users at Ocean View Resort.
 *
 * <p>Uses JPA {@link InheritanceType#JOINED} inheritance strategy so that
 * {@link Customer}, {@link Staff}, and {@link Manager} each have their own
 * database table joined on the shared primary key.</p>
 *
 * <h3>Fields</h3>
 * <ul>
 *   <li>{@code username} – unique login identifier (3-50 characters).</li>
 *   <li>{@code password} – BCrypt-hashed password (excluded from {@code toString()}).</li>
 *   <li>{@code firstName / lastName} – user's legal name.</li>
 *   <li>{@code email} – unique e-mail address used for notifications.</li>
 *   <li>{@code phone} – optional contact number (10-15 digits, optional leading +).</li>
 *   <li>{@code role} – access control level (see {@link UserRole}).</li>
 *   <li>{@code isActive} – soft-delete flag; defaults to {@code true}.</li>
 * </ul>
 *
 * @see Customer
 * @see Staff
 * @see Manager
 */
@Entity
@Table(name = "users", indexes = {
        @Index(name = "idx_users_username", columnList = "username"),
        @Index(name = "idx_users_email", columnList = "email")
})
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Inheritance(strategy = InheritanceType.JOINED)
public class User {

    /** UUID primary key, auto-generated by JPA. */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private String id;

    /** Unique login username (3-50 characters). */
    @Column(unique = true, nullable = false, length = 50)
    @NotBlank(message = "Username is required")
    @Size(min = 3, max = 50, message = "Username must be between 3 and 50 characters")
    private String username;

    /**
     * BCrypt-hashed password.
     * Excluded from {@code toString()} to prevent accidental logging.
     */
    @Column(nullable = false)
    @NotBlank(message = "Password is required")
    @ToString.Exclude
    private String password;

    /** User's first name (up to 100 characters). */
    @Column(name = "first_name", nullable = false, length = 100)
    @NotBlank(message = "First name is required")
    @Size(max = 100, message = "First name must not exceed 100 characters")
    private String firstName;

    /** User's last name (up to 100 characters). */
    @Column(name = "last_name", nullable = false, length = 100)
    @NotBlank(message = "Last name is required")
    @Size(max = 100, message = "Last name must not exceed 100 characters")
    private String lastName;

    /** Unique e-mail address for account identification and notifications. */
    @Column(unique = true, nullable = false, length = 150)
    @Email(message = "Email must be valid")
    @NotBlank(message = "Email is required")
    private String email;

    /** Optional phone number (10-15 digits with optional leading '+'). */
    @Column(length = 20)
    @Pattern(regexp = "^[+]?[0-9]{10,15}$", message = "Phone number must be 10-15 digits")
    private String phone;

    /** Role-based access level for the user. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRole role;

    /** Whether the account is active; {@code false} represents a soft-deleted user. */
    @Column(name = "is_active")
    @Builder.Default
    private boolean isActive = true;

    /** Timestamp of record creation (set automatically, never updated). */
    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private LocalDateTime createdAt;

    /** Timestamp of the last update (set automatically on every update). */
    @UpdateTimestamp
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    /**
     * Returns the user's full name by concatenating first and last names.
     *
     * @return full name string
     */
    @Transient
    public String getFullName() {
        return firstName + " " + lastName;
    }
}
